pipeline {
    agent any
    environment {
        DOCKERFILE_PATH = 'clinicalx/devops/Dockerfile'
        DOCKER_IMAGE = 'lorkorblaq/clincalx_main:latest'
    }
    triggers {
        pollSCM '*/5 * * * *'
    }
    stages {
        stage('checkout') {
            steps {
                git(url: 'https://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@github.com/lorkorblaq/clinicalx', branch: 'main')
            }
        }
        stage('Build') {
            steps {
                echo "Building.."
                sh """
                docker build -f ${DOCKERFILE_PATH} -t ${DOCKER_IMAGE} .
                """
                // sh '''
                // cd myapp
                // pip install -r requirements.txt
                // '''
            }
        }
        stage('Test') {
            steps {
                echo "Testing.."
    
            }
        }
        stage('Deliver') {
            steps {
                echo 'Deliver....'
                sh '''
                echo "doing delivery stuff.."
                '''
            }
        }
    }
}
